import { Inter } from "next/font/google";
import { Nav } from "../components/Navbar";
import Head from "next/head";
import "../styles/globals.css";
import type { AppProps } from "next/app";
const inter = Inter({ subsets: ["latin"] });
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { goerli } from "wagmi/chains";

const chains = [goerli];
const walletConnectProjectId = process.env
  .NEXT_PUBLIC_WALLECT_CONNECT_ID as string;

const { publicClient } = configureChains(chains, [
  w3mProvider({ projectId: walletConnectProjectId }),
]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId: walletConnectProjectId, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className={inter.className}>
      <Head>
        <title>NFT Guardian</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WagmiConfig config={wagmiConfig}>
          <Nav />
          <Component {...pageProps} />
          <Web3Modal
            projectId={walletConnectProjectId}
            ethereumClient={ethereumClient}
          />
        </WagmiConfig>
      </main>
    </div>
  );
}

export default MyApp;
